version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Run tests and sent to codecov
          command: ./gradlew test jacocoMerge
      - codecov/upload:
          file: build/jacoco/report.xml
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - store_test_results:
          path: build/jacoco/allTestCoverage.exec
      - store_artifacts:
          path: build/jacoco/allTestCoverage.exec
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build & push docker images
          command: ./gradlew build jib -x test -Djib.to.auth.username=$DOCKER_USERNAME -Djib.to.auth.password=$DOCKER_PASSWORD
workflows:
  version: 2.1
  workflow:
    jobs:
      - build
        filters:
          branches:
            only:
              - master
              - develop
notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/bc2a3e3314343a3948ea