version: "3.7"

networks:
  front-tier:
  back-tier:

volumes:
  gl_mongo:

services:
  mongodb:
    image: mongo:4.2.1-bionic
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - back-tier
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - gl_mongo:/data/db