version: "3.7"

networks:
  front-tier:
  back-tier:

volumes:
  gl_postgres:

services:
  postgres:
    image: postgres:12
    build:
      context: ./docker-postgresql-multiple-databases
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - back-tier
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_MULTIPLE_DATABASES=event_service,user_service,auth_service,donation_service
    volumes:
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
      - gl_postgres:/var/lib/postgresql