spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false #in order to use spring load balancer
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
  webflux:
    date-format: dd/MM/yyyy HH:mm:ss

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://greenlight.local:8443/auth/realms/GreenLight/protocol/openid-connect/certs

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8888/eureka/
  instance:
    metadata-map:
      rsocket-port: ${spring.rsocket.server.port}