server:
  port: 8100

spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://postgres:5432/auth_service
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      idleTimeout: 30000
      connectionTimeout: 30000

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  rsocket:
    server:
      port: 7500

security:
  oauth2:
    resource:
      filter-order: 3
    client:
      client-id: auth-service
      client-secret: 123456
    validity:
      access-token: 3600
      refresh-token: 86400