server:
  port: 8000

spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/event_service
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  datasource:
    url: jdbc:postgresql://postgres:5432/event_service
    type: org.postgresql.ds.PGSimpleDataSource
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  rsocket:
    server:
      port: 7500

  cache:
    cache-names: event_likes
    caffeine:
      spec: maximumSize=500
