server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

spring:
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
  webflux:
    date-format: dd/MM/yyyy HH:mm:ss
  data:
    mongodb:
      username: mongo
      password: password
      database: event_service
      port: 27017
      host: localhost
      authentication-database: admin