server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

spring:
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
  webflux:
    date-format: dd/MM/yyyy HH:mm:ss
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/event_service
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://postgres:5432/event_service
    type: org.postgresql.ds.PGSimpleDataSource
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml