server:
  port: 8000

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/event_service
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/event_service
    type: org.postgresql.ds.PGSimpleDataSource
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  rsocket:
    server:
      port: 7502

security:
  oauth2:
    client:
      client-id: event-service
      client-secret: 123456

greenlight:
  security:
    oauth2:
      resource:
        auto-configure: true