server:
  port: 8200

spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/user_service
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  datasource:
    url: jdbc:postgresql://postgres:5432/user_service
    type: org.postgresql.ds.PGSimpleDataSource
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  rsocket:
    server:
      port: 7500
