server:
  port: 8888
spring:
  cloud:
    discovery:
      enabled: true
    config:
      server:
        native:
          search-locations: classpath:/config
  profiles:
    active: native
  application:
    name: config-server
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

